### ISSUE TITLE
New Nominatim 3.1/Ubuntu16 installation returns no results after import

### ISSUE THREAD

**Issue by kshankar2017** [openstreetmap/Nominatim#1063]
Tried using master nominatim and it worked.
https://nominatim.openstreetmap.org/reverse?format=json&lat=32.56499&lon=-95.82108&addressdetails=1
However using my built Nominatim3.1.0 gives error. 
http://li657-60.members.linode.com/nominatim/reverse?format=json&lat=32.56499&lon=-95.82108&debug=1
There are 2 unique errors shown below. However the format=html works correctly.
1) string(672) "select place_id,parent_place_id,rank_search,country_code, ST_distance(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry) as distance FROM placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry, 0.0016) AND rank_search != 28 and rank_search >= 26 and (name is not null or housenumber is not null or rank_search between 26 and 27) and class not in ('waterway','railway','tunnel','bridge','man_made') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), centroid, 0.0016)) ORDER BY distance ASC limit 1"
2) string(707) "select place_id,parent_place_id,rank_search,country_code, ST_distance(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry) as distance FROM (SELECT * FROM placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry, 0.0128) LIMIT 1000) as p WHERE rank_search != 28 and rank_search >= 22 and (name is not null or housenumber is not null or rank_search between 26 and 27) and class not in ('waterway','railway','tunnel','bridge','man_made') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), centroid, 0.0128)) ORDER BY distance ASC limit 1" string(707) "select place_id,parent_place_id,rank_search,country_code, ST_distance(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry) as distance FROM (SELECT * FROM placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), geometry, 0.0256) LIMIT 1000) as p WHERE rank_search != 28 and rank_search >= 22 and (name is not null or housenumber is not null or rank_search between 26 and 27) and class not in ('waterway','railway','tunnel','bridge','man_made') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-95.82108,32.56499),4326), centroid, 0.0256)) ORDER BY distance ASC limit 1" NULL array(0) { }

Please help me understand why this is occuring.

**Comment by mtmail** [comment]
The SQL queries you see is Nominatim trying to find a place in close proximity (I think 50cm), then slowly increases the radius until it gives up. The `Unable to geocode` message indicates more that no place was found than a database query error. 

When I do a forward search for "Texas", or actually any country or place name, nothing is found. http://li657-60.members.linode.com/nominatim/search.php?q=texas

Did the import finish completely and successfully? How many database records do you have in the `place`, `placex`, `word` tables? What does `SELECT indexed_status, count(*) FROM placex GROUP BY indexed_status;` return? (ideally all should be `0`)

**Comment by kshankar2017** [comment]
Count of rows in place, placex and words are 277667, 275796 and 182606 respectively.
SELECT indexed_status, count(*) FROM placex GROUP BY indexed_status; returns
 indexed_status | count
----------------+--------
              1 | 275796

You were right apparently there was an error at the end of import process. It is complaining about the absence of gb_postcode table.
I did follow the outlined wiki article and download gb_postcode_data.sql.gz which contains a sql statement to copy gb_postcode table when unzipped. Maybe that did not happen.
Do I really need gb_postcode table during the run of setup.php ?

Here is the error.

2018-06-14 07:10:50 == Reanalysing database
NOTICE:  no non-null/empty features, unable to compute statistics
NOTICE:  no non-null/empty features, unable to compute statistics
Latest data imported from 2018-06-12T02:00:42Z.
2018-06-14 07:11:00 == Calculate Postcodes
PHP Warning:  pg_query(): Query failed: ERROR:  relation "gb_postcode" does not exist
LINE 1: ...l('seq_place'), 1, 'gb', postcode, geometry  FROM gb_postcod...
                                                             ^ in /srv/nominatim/Nominatim-3.1.0/build/utils/setup.php on line 553
ERROR: ERROR:  relation "gb_postcode" does not exist
LINE 1: ...l('seq_place'), 1, 'gb', postcode, geometry  FROM gb_postcod...
                                                             ^
ERROR:  relation "gb_postcode" does not exist
LINE 1: ...l('seq_place'), 1, 'gb', postcode, geometry  FROM gb_postcod...

**Comment by kshankar2017** [comment]
Fixed the above problem by downloading gb_postcode_table.sql from
https://github.com/openstreetmap/Nominatim/blob/master/data/gb_postcode_table.sql
It seems like only gb_postcode_data.sql.gz is available from nominatim.org/data, but not the table. Luckily Lonvia had posted the above link.
Now I verified that import completed Ok with a warning.
Summary of warnings:
  * external UK postcode table not found.
2018-06-14 08:47:13 == Setup finished.

Count of rows in place, placex and word are 277667, 275796 and 228128 respectively.
SELECT indexed_status, count(*) FROM placex GROUP BY indexed_status; returns
indexed_status | count
----------------+--------
1 | 275796
Now 
http://li657-60.members.linode.com/nominatim/search.php?q=texas works.
Also
http://li657-60.members.linode.com/nominatim/search.php?format=json&q=texas works.

However the lookups don't work for any city in state of TX, but it works very well for many cities in state of NM.
I combined the 2 states using
osmconvert texas-latest.osm.pbf --out-o5m | osmconvert new-mexico-latest.osm.pbf -o=txPlusnm.pbf
For example
http://li657-60.members.linode.com/nominatim/search.php?format=json&q=Houston+texas
returns [ ] json array.

**Comment by lonvia** [comment]
`gb_postcode_table.sql` is contained in the Nominatim-3.1.0 tarball, I just rechecked. There should be no issue running the install without downloading the GB postcode data.

**Comment by mtmail** [comment]
> I combined the 2 states using
osmconvert texas-latest.osm.pbf --out-o5m | osmconvert new-mexico-latest.osm.pbf -o=txPlusnm.pbf

When I run this I get an `Output has been terminated.` error and the output is about the filesize of New Mexico. I think you forgot  a dash behind the second `osmconvert`. See https://help.openstreetmap.org/questions/48843/merging-two-or-more-geographical-areas-to-import-two-or-more-osm-files-in-nominatim/48857

Before starting `utils/setup.php` again, delete the database using `dropdb nominatim`.

**Comment by lonvia** [comment]
The original error was resolved, I believe. Closing.
