### ISSUE TITLE
No result if request contains param postcode

### ISSUE THREAD

**Issue by looser** [openstreetmap/Nominatim#537]
This is working:
- https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&street=Rodger+Rd&format=json
- https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&format=json

This is not working:
 -https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&street=Rodger+Rd&postalcode=3759&format=json
- https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&postalcode=3759&format=json

But the postal code is correct and openstreetmap.org is also able to find the address
http://www.openstreetmap.org/search?query=5783%20Panton%20Hill#map=14/-37.6414/145.2390

**Comment by looser** [comment]
Any opinions on that?
I consider this as a bug

**Comment by lonvia** [comment]
The postcode is not in OSM. Nominatim is not able to do a fuzzy match where it excludes part of the query. The only exception are house numbers. That's why postcode still seem to be excluded sometimes: Nominatim assumes they might be a house number. (And, yes, the information that it is a postcode is lost to Nominatim even when you use the postalcode=123 parameter. That's another construction site.)

Given that the format of postcodes is rather well defined on a country level, we'll might give it some special treatment in the future and also allow it to be dropped. But that requires to solve #403 first.

**Comment by looser** [comment]
> And, yes, the information that it is a postcode is lost to Nominatim even when you use the postalcode=123 parameter

What do you exactly mean with "the information is lost" ? Should i never send a request which contains a postalcode as it is lost anyways?

**Comment by lonvia** [comment]
When you add postalcode=123 to your query, Nominatim does normally not retain the information that 123 is a postcode. The number will be matched against anything including house numbers.

**Comment by looser** [comment]
This is still a show stopper. 
I have not figured out one combination of params which is always working. I can not omit
the postalcode. There are a ton of Springfield in USA e.g. how am i supposed to get the right one without the postalcode?

In this case, the combination of country & postalcode is not working
https://nominatim.openstreetmap.org/search?country=AU&postalcode=3759&format=json

But country, city & street is working. 
https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&street=Rodger+Rd9&format=json

In this case country, city & postalcode is not working
https://nominatim.openstreetmap.org/search?city=Rendsburg&country=DE&format=json&postalcode=24768

but instead country & postalcode is working
https://nominatim.openstreetmap.org/search?country=DE&format=json&postalcode=24768

**Comment by lbuser1** [comment]
Is there any progress on this issue?

We have many cities here in germany with the same name and same street names.
Is there a workaround to get the right location?

**Comment by lonvia** [comment]
Not that I'm aware of. So far nobody has volunteered to take #403 on.

**Comment by joh-klein** [comment]
@lonvia If I understand [your comment](https://github.com/openstreetmap/Nominatim/issues/750#issuecomment-308039387) on #750 correctly, you started to recalculate countries. So does that mean that the problem is fixed? (And could you please recalculate Germany if you haven't done so already?)

**Comment by lonvia** [comment]
#750 is unrelated to this issue.

**Comment by lonvia** [comment]
Fixed with #782.

**Comment by looser** [comment]
Thank you very much for spending time. 

One issue is still open in my opinion.

This is still not working

https://nominatim.openstreetmap.org/search?city=Panton+Hill&country=AU&postalcode=3759&format=json

But the postal code is correct and openstreetmap.org is also able to find the address
http://www.openstreetmap.org/search?query=5783%20Panton%20Hill#map=14/-37.6414/145.2390

**Comment by lonvia** [comment]
The postcode 3759 is still not known to OSM. Currently the requirement is still that it at least exists somewhere in OSM. If you happen to know that the postcode is correct, then I suggest you add it to OSM.
